---
openapi: 3.0.3
info:
  title: eventdb API
  version: 1.0-SNAPSHOT
paths:
  /events:
    get:
      tags:
      - Event Publisher Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /events/search:
    post:
      tags:
      - Event Publisher Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /events/searchBy:
    post:
      tags:
      - Event Publisher Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplexSearchDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Event'
  /ingest/add:
    post:
      tags:
      - Event Ingestion Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - ingest
components:
  schemas:
    ComplexSearchDto:
      type: object
      properties:
        anyKeyExactMatch:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        allKeyExactMatch:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        anyKeyOrValueContains:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        allKeyOrValueContains:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        anyKeyOrValueExactMatch:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        allKeyOrValueExactMatch:
          uniqueItems: true
          type: array
          items:
            type: string
          nullable: true
        anyValueForKeyContains:
          uniqueItems: true
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        allValueForKeyContains:
          uniqueItems: true
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        anyValueForKeyExactMatch:
          uniqueItems: true
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
        allValueForKeyExactMatch:
          uniqueItems: true
          type: array
          items:
            type: array
            items:
              type: string
          nullable: true
    Event:
      required:
      - name
      - startDate
      type: object
      properties:
        name:
          type: string
        startDate:
          $ref: '#/components/schemas/ZonedDateTime'
        data:
          type: object
          additionalProperties:
            type: string
          nullable: true
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    SearchDTO:
      type: object
      properties:
        name:
          type: string
          nullable: true
        fromDate:
          type: string
          allOf:
          - $ref: '#/components/schemas/OffsetDateTime'
          nullable: true
        toDate:
          type: string
          allOf:
          - $ref: '#/components/schemas/OffsetDateTime'
          nullable: true
    ZonedDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
